version: 2

models:
  - name: fct_order_items
    description: "Fact table at order-item grain (one row per product per order)."
    columns:
      - name: order_item_id
        description: "Unique identifier for the order line item."
        tests: [not_null, unique]

      - name: order_id
        description: "Order identifier (FK to fct_orders)."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('fct_orders')
                field: order_id

      - name: product_id
        description: "Product identifier (FK to dim_products)."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_id

      - name: line_amount
        description: "Monetary amount for the line item."
        tests: [not_null]

  - name: fct_orders
    description: "Fact table at order grain (one row per order)."
    columns:
      - name: order_id
        description: "Unique identifier for the order."
        tests: [not_null, unique]

      - name: customer_id
        description: "Customer identifier (FK to dim_customers)."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id

      - name: order_date
        description: "Order date (derived from order timestamp)."
        tests: [not_null]

      - name: items_count
        description: "Number of line items in the order."
        tests: [not_null]

      - name: order_amount
        description: "Total order amount (sum of line_amount for the order)."
        tests: [not_null]

      - name: is_first_order
        description: "True if this order is the customer's first order date."
        tests: [not_null]

  - name: dim_customers
    description: "Customer dimension (one row per customer)."
    columns:
      - name: customer_id
        description: "Unique identifier for the customer."
        tests: [not_null, unique]

      - name: first_order_date
        description: "Date of the customer's first order."
        tests: [not_null]

      - name: last_order_date
        description: "Date of the customer's most recent order."
        tests: [not_null]

      - name: total_orders
        description: "Total number of orders placed by the customer."
        tests: [not_null]

      - name: total_revenue
        description: "Total revenue generated by the customer."
        tests: [not_null]

      - name: avg_order_value
        description: "Average order value for the customer."
        tests: [not_null]

      - name: is_repeat_customer
        description: "True if the customer has placed more than one order."
        tests: [not_null]

  - name: dim_products
    description: "Product dimension (one row per product)."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
        tests: [not_null, unique]

      - name: product_name
        description: "Human-readable product name."
        tests: [not_null]

      - name: category
        description: "Product category."
        tests: [not_null]

      - name: brand
        description: "Product brand."
        tests: [not_null]

      - name: sku
        description: "Stock Keeping Unit."
        tests: [not_null]

      - name: price
        description: "Unit price for the product (aliased from unit_price)."
        tests: [not_null]

      - name: currency
        description: "Currency code for price."
        tests: [not_null]

      - name: is_active
        description: "Whether the product is active."
        tests: [not_null]

  - name: mart_customer_metrics
    description: "Customer-level analytics mart with revenue, recency, and ordering behavior metrics."
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: first_order_date
        tests: [not_null]
      - name: last_order_date
        tests: [not_null]
      - name: total_orders
        tests: [not_null]
      - name: lifetime_revenue
        tests: [not_null]
      - name: days_since_last_order
        tests: [not_null]
      - name: is_active_last_30d
        tests: [not_null]
      - name: is_repeat_customer
        tests: [not_null]
      - name: customer_segment
        tests: [not_null]