version: 2

sources:
  - name: iceberg
    database: "gcp-iceberg-dbt"
    schema: "analytics_iceberg"
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: products